### ISSUE TITLE
Fix unintended consequences

### ISSUE THREAD

**Issue by g4b1nagy** [mess110/declaratie#1]
Since coordinates are hard-coded and my screen resolution / window placement does not match the one in the README.md file, the script actually clicked inside my mobile banking application sending $5.000 to my electricity supplier.
I rate this a 5/7.

**Comment by mess110** [comment]
https://github.com/mess110/declaratie/commit/3436b685906f7bf5b979fff93dcc1b0abc6b8256#diff-04c6e90faac2675aa89e2176d2eec7d8R45

We take PRs not issues :pager:
